import type { NexaProduct } from '@/types';

export const sampleProducts: NexaProduct[] = [
  {
    id: '1', apiId: 101, slug: 'chatgpt-plus-monthly',
    name: 'ChatGPT Plus — 1 Month',
    description: 'Premium ChatGPT Plus subscription with GPT-4o, DALL·E, and advanced features.',
    category: 'AI Tools', provider: 'OpenAI',
    price: 18.99, originalPrice: 24.99, currency: 'USD',
    deliveryType: 'LINK', inStock: true, stockCount: 145,
    durationDays: 30, warrantyDays: 7, instantDelivery: true,
    image: '', rating: 4.8, reviewCount: 2340,
    featured: true, trending: true, isNew: false,
  },
  {
    id: '2', apiId: 102, slug: 'gemini-pro-monthly',
    name: 'Gemini Pro — 30 Days',
    description: 'Google Gemini Pro subscription with advanced AI features.',
    category: 'AI Tools', provider: 'Google',
    price: 12.50, originalPrice: 15.00, currency: 'USD',
    deliveryType: 'LINK', inStock: true, stockCount: 98,
    durationDays: 30, warrantyDays: 7, instantDelivery: true,
    image: '', rating: 4.6, reviewCount: 1850,
    featured: true, trending: true, isNew: false,
  },
  {
    id: '3', apiId: 103, slug: 'claude-pro-monthly',
    name: 'Claude Pro — 1 Month',
    description: 'Anthropic Claude Pro with extended context and priority access.',
    category: 'AI Tools', provider: 'Anthropic',
    price: 20.00, originalPrice: 20.00, currency: 'USD',
    deliveryType: 'LINK', inStock: true, stockCount: 67,
    durationDays: 30, warrantyDays: 7, instantDelivery: true,
    image: '', rating: 4.9, reviewCount: 920,
    featured: true, trending: false, isNew: true,
  },
  {
    id: '4', apiId: 201, slug: 'netflix-premium-1m',
    name: 'Netflix Premium — 1 Month',
    description: 'Netflix Premium UHD plan, 4 screens, global access.',
    category: 'Streaming', provider: 'Netflix',
    price: 8.99, originalPrice: 15.49, currency: 'USD',
    deliveryType: 'READY_ACCOUNT', inStock: true, stockCount: 210,
    durationDays: 30, warrantyDays: 7, instantDelivery: true,
    image: '', rating: 4.5, reviewCount: 5430,
    featured: true, trending: true, isNew: false,
  },
  {
    id: '5', apiId: 202, slug: 'spotify-premium-3m',
    name: 'Spotify Premium — 3 Months',
    description: 'Ad-free music streaming with offline downloads.',
    category: 'Streaming', provider: 'Spotify',
    price: 9.99, originalPrice: 29.97, currency: 'USD',
    deliveryType: 'LINK', inStock: true, stockCount: 320,
    durationDays: 90, warrantyDays: 7, instantDelivery: true,
    image: '', rating: 4.7, reviewCount: 3890,
    featured: false, trending: true, isNew: false,
  },
  {
    id: '6', apiId: 301, slug: 'capcut-pro-1y',
    name: 'CapCut Pro — 1 Year',
    description: 'Professional video editing with AI tools, no watermark.',
    category: 'Software', provider: 'ByteDance',
    price: 24.99, originalPrice: 89.99, currency: 'USD',
    deliveryType: 'COUPON', inStock: true, stockCount: 156,
    durationDays: 365, warrantyDays: 30, instantDelivery: true,
    image: '', rating: 4.8, reviewCount: 1560,
    featured: true, trending: true, isNew: false,
  },
  {
    id: '7', apiId: 302, slug: 'canva-pro-1y',
    name: 'Canva Pro — 1 Year',
    description: 'All-in-one design platform with premium templates and AI.',
    category: 'Software', provider: 'Canva',
    price: 19.99, originalPrice: 119.99, currency: 'USD',
    deliveryType: 'LINK', inStock: true, stockCount: 89,
    durationDays: 365, warrantyDays: 14, instantDelivery: true,
    image: '', rating: 4.6, reviewCount: 2780,
    featured: false, trending: false, isNew: true,
  },
  {
    id: '8', apiId: 401, slug: 'nordvpn-2y',
    name: 'NordVPN — 2 Year Plan',
    description: 'Top-tier VPN with threat protection and 5000+ servers.',
    category: 'VPN', provider: 'Nord Security',
    price: 69.99, originalPrice: 223.83, currency: 'USD',
    deliveryType: 'LINK', inStock: true, stockCount: 500,
    durationDays: 730, warrantyDays: 30, instantDelivery: true,
    image: '', rating: 4.7, reviewCount: 4120,
    featured: false, trending: false, isNew: false,
  },
  {
    id: '9', apiId: 501, slug: 'google-play-50',
    name: 'Google Play — $50 Gift Card',
    description: 'Redeem for apps, games, movies, books on Google Play.',
    category: 'Gift Cards', provider: 'Google',
    price: 45.00, originalPrice: 50.00, currency: 'USD',
    deliveryType: 'COUPON', inStock: true, stockCount: 620,
    durationDays: 0, warrantyDays: 0, instantDelivery: true,
    image: '', rating: 4.9, reviewCount: 890,
    featured: false, trending: false, isNew: false,
  },
  {
    id: '10', apiId: 601, slug: 'xbox-game-pass-ultimate-3m',
    name: 'Xbox Game Pass Ultimate — 3 Months',
    description: 'Hundreds of games, day-one releases, Xbox Live Gold included.',
    category: 'Gaming', provider: 'Microsoft',
    price: 24.99, originalPrice: 50.97, currency: 'USD',
    deliveryType: 'COUPON', inStock: true, stockCount: 180,
    durationDays: 90, warrantyDays: 7, instantDelivery: true,
    image: '', rating: 4.8, reviewCount: 1650,
    featured: false, trending: true, isNew: false,
  },
  {
    id: '11', apiId: 701, slug: 'aws-100-credits',
    name: 'AWS — $100 Cloud Credits',
    description: 'Amazon Web Services credits for cloud computing, valid 1 year.',
    category: 'Cloud Services', provider: 'AWS',
    price: 15.99, originalPrice: 100.00, currency: 'USD',
    deliveryType: 'COUPON', inStock: true, stockCount: 45,
    durationDays: 365, warrantyDays: 7, instantDelivery: true,
    image: '', rating: 4.4, reviewCount: 340,
    featured: false, trending: false, isNew: true,
  },
  {
    id: '12', apiId: 801, slug: 'youtube-premium-3m',
    name: 'YouTube Premium — 3 Months',
    description: 'Ad-free YouTube, background play, YouTube Music included.',
    category: 'Premium Accounts', provider: 'Google',
    price: 7.99, originalPrice: 35.97, currency: 'USD',
    deliveryType: 'READY_ACCOUNT', inStock: true, stockCount: 275,
    durationDays: 90, warrantyDays: 7, instantDelivery: true,
    image: '', rating: 4.6, reviewCount: 2130,
    featured: true, trending: false, isNew: false,
  },
];

export const reviews = [
  { id: 1, name: 'Sarah K.', role: 'Digital Creator', rating: 5, text: 'Nexa is my go-to for all AI subscriptions. Instant delivery every single time. The interface is gorgeous and checkout takes seconds.', avatar: 'SK' },
  { id: 2, name: 'Marcus J.', role: 'Software Engineer', rating: 5, text: 'I was skeptical at first but the delivery is truly instant. Got my ChatGPT Plus key in under 30 seconds. Pricing is unbeatable.', avatar: 'MJ' },
  { id: 3, name: 'Elena R.', role: 'Content Strategist', rating: 5, text: 'The best marketplace for digital products. Premium feel, great support, and the automatic delivery system is flawless.', avatar: 'ER' },
  { id: 4, name: 'David L.', role: 'Startup Founder', rating: 4, text: 'Solid platform for sourcing digital tools. The API integration means stock is always accurate. Would love more crypto payment options.', avatar: 'DL' },
  { id: 5, name: 'Aisha M.', role: 'Designer', rating: 5, text: 'Beautiful UI and incredibly fast. The dark mode is gorgeous and every detail feels premium. This is how all marketplaces should look.', avatar: 'AM' },
  { id: 6, name: 'Tom H.', role: 'IT Consultant', rating: 5, text: 'Enterprise-grade platform at consumer prices. The automated delivery system is reliable and the product range keeps growing.', avatar: 'TH' },
];

export const faqItems = [
  { q: 'How fast is delivery?', a: 'Most products are delivered instantly after payment. In rare cases, it may take up to 5 minutes. You\'ll receive your product link, code, or account credentials directly in your dashboard.' },
  { q: 'What payment methods do you accept?', a: 'We accept Stripe (credit/debit cards), PayPal, Apple Pay, Google Pay, cryptocurrency (BTC, ETH, USDT), Binance Pay, and wallet balance.' },
  { q: 'Do products come with warranty?', a: 'Yes! Most products include a warranty period (typically 7-30 days depending on the product). If your product stops working within the warranty period, we\'ll replace it free of charge.' },
  { q: 'Is it safe to buy digital products here?', a: 'Absolutely. We use enterprise-grade encryption, secure payment processing, and never expose sensitive credentials publicly. All deliveries are made through encrypted channels.' },
  { q: 'Can I get a refund?', a: 'We offer refunds within the warranty period if the product is defective. Due to the digital nature of our products, we cannot offer refunds for change of mind.' },
  { q: 'How does the automatic delivery work?', a: 'Once your payment is confirmed, our system automatically contacts our partner suppliers, reserves your product, and delivers it to your dashboard and email — all within seconds.' },
];

export const stats = [
  { value: '50K+', label: 'Happy Customers' },
  { value: '99.8%', label: 'Delivery Rate' },
  { value: '500+', label: 'Digital Products' },
  { value: '24/7', label: 'Support' },
];
